import { washeMan } from "../utils/assets-jpg";

export const LaundryRequests = [
  {
    img: washeMan,
    status: "pending",
    id: 1,
    date: "25th Jun 2023, 04:45 PM",
    firstName: "Jenny",
    lastName: "Will",
    requestType: "pick-up",
    distance: "5 mins away",
    location: "little rock",
  },
  {
    img: washeMan,
    status: "ongoing",
    id: 2,
    date: "25th Jun 2023, 04:45 PM",
    firstName: "Rhoda",
    lastName: "Benson",
    requestType: "delivery",
    distance: "5 mins away",
    location: "little rock",
  },
  {
    img: washeMan,
    status: "completed",
    id: 3,
    date: "25th Jun 2023, 04:45 PM",
    firstName: "Jenny",
    lastName: "Wilson",
    requestType: "delivery",
    distance: "5 mins away",
    location: "little rock",
  },
  {
    img: washeMan,
    status: "completed",
    id: 3,
    date: "25th Jun 2023, 04:45 PM",
    firstName: "John",
    lastName: "Peckwood",
    requestType: "delivery",
    distance: "5 mins away",
    location: "little rock",
  },
  {
    img: washeMan,
    status: "pending",
    id: 4,
    date: "25th Jun 2023, 04:45 PM",
    firstName: "Penny",
    lastName: "Lockwood",
    requestType: "pick-up",
    distance: "5 mins away",
    location: "little rock",
  },
];
