import { ScrollView, StyleSheet } from "react-native";
import { View } from "../libs/view";
import { XStack, YStack, useTheme } from "tamagui";
import { Text } from "../libs/text";
import { InputBox } from "../input";
import { Button } from "../button";
import { SuccessModal } from "../modal";
import { Dispatch, SetStateAction, useState } from "react";

type props = {
  //   setShow: Dispatch<SetStateAction<boolean>>;
  //   setOpenCreditCard: Dispatch<SetStateAction<boolean>>;
  onPress: () => void;
};
export const CreditCard = ({ onPress }: props) => {
  const theme = useTheme();

  return (
    <>
      <View width={"100%"} paddingHorizontal={28}>
        <YStack height={"auto"}>
          <ScrollView
            showsVerticalScrollIndicator={false}
            style={styles.scrollview}
          >
            <View height="80%" width="100%" style={styles.container}>
              <InputBox
                label="Card number"
                keyboardType="number-pad"
                placeholder="0000 0000 0000 0000"
              />
              <InputBox
                label="Expiry date"
                keyboardType="number-pad"
                placeholder="MM/YY"
              />
              <InputBox
                label="CVV"
                keyboardType="number-pad"
                placeholder="MM/YY"
              />
              <InputBox
                label="Expiry date"
                keyboardType="number-pad"
                placeholder="MM/YY"
              />
              <InputBox label="Account name" placeholder="--autogenerated--" />
            </View>
          </ScrollView>
          <View paddingTop={30}>
            <Button title="Add card" onPress={onPress} />
          </View>
        </YStack>
      </View>
    </>
  );
};
const styles = StyleSheet.create({
  container: {
    width: "100%",
    marginTop: 20,
  },
  card: {
    width: "100%",
    height: "100%",
  },
  cardImage: {
    borderRadius: 20,
  },
  atm: {
    shadowColor: "rgba(103, 114, 229, 0.08)",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    // Shadow for Android
    elevation: 1,
  },
  active: {
    width: 16,
    height: 16,
    borderRadius: 50,
    borderWidth: 4,
    borderColor: "#00D158",
  },
  inactive: {
    width: 16,
    height: 16,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: "#DFE2E2",
  },
  scrollview: {
    height: "79%",
  },
});
